drop index if exists public.appointment_product_usages_stock_movement_id_idx;

create index appointment_product_usages_stock_movement_id_idx on public.appointment_product_usages (stock_movement_id);;
